<?php
/**
 * @var $block \Hokodo\BnplCommerce\Block\Adminhtml\Company\Edit\CreditBalance
 */
?>
<?php if ($block->isEligible() && $block->getCompany()->getCompanyId()): ?>
<ul class="credit-balance-list" data-role="credit-balance">
        <li class="credit-balance-item">
            <p class="credit-balance-label"><?= $block->escapeHtml(__('Credit Limit:')) ?></p>
            <span class="credit-balance-price">
                <?= $block->escapeHtml($block->getAmount()) ?>
            </span>
        </li>
        <li class="credit-balance-item">
            <p class="credit-balance-label"><?= $block->escapeHtml(__('Outstanding Balance:')) ?></p>
            <span class="credit-balance-price">
                <?= $block->escapeHtml($block->getAmountInUse()) ?>
            </span>
        </li>
        <li class="credit-balance-item">
            <p class="credit-balance-label"><?= $block->escapeHtml(__('Available Credit:')) ?></p>
            <span class="credit-balance-price">
                <?= $block->escapeHtml($block->getAmountAvailable()) ?>
            </span>
        </li>
</ul>
<?php endif; ?>
